// Given: A DNA string
// Return: Four Integers

tallyDna = (dna_string) => {
  a = 0;
  c = 0;
  g = 0;
  t = 0;
  for (const dna in dna_string) {
    n = dna_string[dna]
    if (n == "A") {
      a += 1;
    }
    else if (n == "C") {
      c += 1
    }
    else if (n == "G") {
      g += 1;
    }
    else if (n == "T") {
      t += 1;
    }
  }
  let tally = [a, c, g, t]
  return [...tally ]
};

tallyDna2 = (dna_string) => {
  var tally = {
    'A': 0, 'C': 0,
    'G': 0, 'T': 0
  };
  for (const dna in dna_string) {
    n = dna_string[dna]
    tally[n] += 1
  }
  return tally;
};

console.log(tallyDna('AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'))

console.log(tallyDna2('AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC'))

console.log(tallyDna('TTTATGGAACAGGTTCTACCTTCTCCTGGCGTTGTAATGACTGCATAGAATAATCGGCCTAATAGAGTATGTACTTCCACACCGGCTGGGCTGCCGGGTCCTATAAATCTTGGACGCGGTAGATGATCCGTAAGTGCGACCCGCGATGTCCTTGTAGCTTGATGTAACACATCACTGAGGCGGACACACCCGTCCCGTAGAGGGACGTCCCTGATGTACCCTGGCCATGGTTTTAATTGTAGGCTGCACTAGCTATGAAAATGTGCGCGCGTCTCGCCCGGAGCTGCCGCTCGTGCAGCGGATGAGAAACGGCCGCTGTGTCCATTCAATTTCGGAACCGTTCCCTTCTTGTGAATTGAAACATTCACGACTACATACCTTAGACAGGTCTCTATAGTCTCCAGCCAAAAGCCGGCTTGCGCCCGATCGGCGATTCTACGAATTTGTCGTAACACCCTCGAAGGGGGCCTGGGGTCTTTAGTACTTCCACAAAACGCTAGGTGAACGCACCGTTAGGATTGGTACCGTAGTGAGACATCATTCCTGCACTGTTTGCAACATCGCTCATACTCCTTCATAGCGCCCATCCATTGTTACAGTTGTGGCCTCTTCCTCGCCGAGGAGCAATTTTTGGCTGGTAGAAACCCCCGGTCCGTAAACGCACTGGGTAAGTGCACTCATTTCGATGTACCTTTAACATGCTACTTCTAGGCACAACTGAGTTACACGTTTCGTTCGCCACCTTTTGCAGACCACGCTCCTAACGTATGTATTGGATATAAGGGAACGCGAGTAACTGAATTCTCAATACTGCCTAACTGCTAGCTGTTCTCTTGTCATCCTTGTACAAAGGAATTTTCGGAAAGGCAGACACACAGGGGCTTGTACCGATTAGCGTTGAGAGCCTTTAATGACGTGTCCTTGTG'))