// Input: A DNA string
// Output: A transcribed RNA string

transcribe = (dnaString) => {
  var dnaString2 = ""
  var c = "";
  for (let i in dnaString) {
    c = dnaString[i]
    if (c == "T") {
      c = "U"
    }
    dnaString2 += c;
  }
  return dnaString2
}

var problemArchive = "GATGGAACTTGACTACGTAAATT"

var problemString = "ATTCCTCGCATTTCCTTGAATTCCCATCAAAGGAACCTGACGCCCAGTCGGTTGATCAGATGCAAAGGATACGATAGCGCTTATACTTTCCTACGCCGTGGGCTGCTAACATCTATACTTGTTTAAAAAGACATGGTGGTCATGTCTCTCGGCACAATGCTATGTTATCACCTTGCAAGGGTGTCGCCGTTCGGGTCTGATGAGTCAGCAACCCCTTCCACACGTTGATAAGGCGTAAAGATTTGTGAAGGATACGTTGGGCCGCGTTACTCATGAAGCCAGAGATTCCAATTAGGGACTCTATCTCATAATTCGTAGTCTTTTCTGGATCCTGAGCACTATCTTCTAATTCAGTTAGGCGAGGCGGCAAGTCAACGCAGAGTCAGTAACTGCCGTTGGGTAAGAAAATTCCGTATGTTTGCTCCGTCGGTCATCCTGTGTTAATCAAGTTGCCCGGGATGTTGGATAAACCGCGTGAAAGTAGGCTATGGATGAGATCACGCCAAGGCGGCGGATAAAGGGAGGACCGCTCGGCGGAACATAATGGTCCGTACCGGCGTCAGATAAGTATCCGCGATCTACACCTGCGCGATGGACCCACGGCTAGTGACGTGGATAGTACAGAAATCTAGACATCGGCCACGCAATCTCTCTTAGCAAGAGCAGGGTCGCTAGGAAAAAGCCGCGGTGTGTGTATACGAAATACCGACGTAGAGTTATCACGCCCAATCGGAGTGGACGCTTTTCTGCCTCAAAGTGGCAATGGAGAATTGAAGCTCACGGAGAGCACGCACTTGGGCATAGTATAGAGGCCATTGATTCCTAGTAATTCAGAAAGTCCGATTAGCTCAGTGCCGGTCATACAAAGATTGCCCAACTTGCATGCTCGTGGCGCCCAGTGATATCCTGAGCGAGTGCAACTTCTCTATTGGTTCGAAATCAGCCCGGAGACGGGA"

console.log(transcribe(problemString))