// Given: DNA string
// Return: reverse compliment of given

compliment = (dnaString) => {
  compDNA = ""
  var comp = {
    'A': 'T', 'C': 'G',
    'G': 'C', 'T': 'A'
  };
  reverseDNA = dnaString.split("").reverse().join("")
  for (const c of reverseDNA) {
    compDNA += comp[c];
  }
  return compDNA;
}

var testString = "AAAACCCGGT"
var problemString = "GGGGGAGTTAGCCCCAGGACGTCGGCTGATTGGCCTTAAGCATATCATATCCTGCTCACGGCCGAAATTGCGCTGAGTACACGAGGCTGGACTCGACATCTTCACCCATTAGGTAGTTACACAATGTTCTGGCAATAAAGAAGGTTTTCAAGTGTACGATAGAACTTAGCACCGAACCCTGTGGATGTTGCGACGCCGTCACGTCTTATATAGGGGAGCAATTAGTACCTGTCTCAAAAAGTGGAATTACTTAAAGCTACGACCCCGTGCGTCAGTATTCTACTTTCGCGCTGTTAGCTCATAACTTAGCCTCTCCTCTCGACGGTAAGCGTCAGATGAACAGACTCGGTATACTCCTGTTCCTTCTAAAAATACATTGTGTAATCGTAAGGAATTTTCATGGTGCATGGAGTACCTAGCAGCCTCTCCCGTATGGCGCCACTAGATTCTGACTTCCAAGCACAAAAGCGGATAATACCTCTGTGCAGCTTTATCACGATGGGTGGTTTGGCAGGGAGTGAAGTCTCCATACCGCCGAGTTCTCATAATACTCACAGGCTGCTATAAGGGTTAGCCCATCTTCCCGCTAAGGGTGCTCCGACGTTTTGATGGGTCCGCTCCAAAGTCCGCTGGGTGACGCGAGCTTGAAATTACCACTAAAGGTCCCTTCTTTTAAGCGCGCTGCGGACCCCCGATCGGAGAAACCAGGTTGGGAGTCGAATAGCCCCTACTTCGTATCCGAATGGGTATAGTACTCTCCTATTCTGCAGACTAAGGTGCGCGGTCTATCGGGTCTCTCGCGACAGATCGCGTACGGTGGTTGGGCAAAGCGAGC"

console.log(compliment(problemString))