# SUBS - https://rosalind.info/problems/subs/

def findMotif(substring, dnaString):
    listIndex = []
    for i in range(len(dnaString)):
        if (substring[0] == dnaString[i]):
            # print ("i : " + str(i))
            # print (substring)
            # print (dnaString[i:i + len(substring)])
            if (substring == dnaString[i:i + len(substring)]):
                # print ("match at " + str(i))
                listIndex.append(str(i + 1))
    return ' '.join(listIndex)
        
# print (findMotif("ATAT", "GATATATGCATATACTT"))

s = findMotif("CTTGAAACT", "CGTCCTTGAAAGAGCTTGAAACTACTTGAAAGGAGTACTTGAAAGTAGGCTCTTGAAAATCTTGAAAACTTGAAACATCACCTTTTAGCTTGAAACTTGAAATATTCTGTGGGTGCTTGAAAGAGGCTTGAAACTTGAAATCTTGAAACTTGAAAACTTGAAACCTTGAAATCCTTGAAACTTGAAAGCTCTTGAAAGCTTGAAACTTGAAAAAGGAACCTTGAAACTTGAAAAAGCTCTTGAAACTTGAAAACTTGAAATACCCTTGAAACGCTCGCTTGAAACTTGAAATGTTGCCTTGAAACCCTAGACTTGAAATCTTGAAATCTTGAAACCTTGAAAGCAGACCAGCCTTGAAACGCTTGAAAAGTCTTGAAAGCTCTTGAAATCCACTTGAAACTTGAAACAGGAACTTGAAATCTTGAAACCTTGAAACCTTGAAAGTGCTTGAAAACTTGAAACTTGAAACTTGAAACTTGAAAGGACTTGAAACTTGAAACCTTGAAAGCTTGAAAAGAGAGCCAATCTTGAAACTTGAAAACTTGAAATTAGTGCGACTTGAAATTGCTTGAAAGACTTCGGCTCTTGAAACCTTGAAACTTGAAATGTTACTTGAAACTTGAAAACTAAGCTTGAAATCTTGAAACACTTGAAATGTGTCTTGAAAGTTGCTTGAAACCTTGAAACTTGAAACTTGAAACTTCTTGAAACGTCAGGTCGAATCGCTTGAAACGGCATCTTGAAAACACGCCTTGAAAACTTGAAACGGACTTGAAACGGGCTTGAAAAACTTGAAACTTGAAACTTGAAATGTTCTTGAAAACTTGAAAGACTTGAAACTTGAAAACTTGAAAAACTTGAAA")

print (s)
